/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IMessageTransmitterV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMessageTransmitterV2__factory>
getContractFactory(name: 'IXReserve', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IXReserve__factory>
getContractFactory(name: 'XReserveRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.XReserveRouter__factory>
getContractFactory(name: 'MockMessageTransmitter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockMessageTransmitter__factory>
getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>
getContractFactory(name: 'MockXReserve', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockXReserve__factory>

  getContractAt(name: 'IMessageTransmitterV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMessageTransmitterV2>
getContractAt(name: 'IXReserve', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IXReserve>
getContractAt(name: 'XReserveRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.XReserveRouter>
getContractAt(name: 'MockMessageTransmitter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockMessageTransmitter>
getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>
getContractAt(name: 'MockXReserve', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockXReserve>

  deployContract(name: 'IMessageTransmitterV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMessageTransmitterV2>
deployContract(name: 'IXReserve', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IXReserve>
deployContract(name: 'XReserveRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.XReserveRouter>
deployContract(name: 'MockMessageTransmitter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMessageTransmitter>
deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>
deployContract(name: 'MockXReserve', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockXReserve>

  deployContract(name: 'IMessageTransmitterV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMessageTransmitterV2>
deployContract(name: 'IXReserve', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IXReserve>
deployContract(name: 'XReserveRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.XReserveRouter>
deployContract(name: 'MockMessageTransmitter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMessageTransmitter>
deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>
deployContract(name: 'MockXReserve', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockXReserve>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  