/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IXReserveInterface extends Interface {
    getFunction(nameOrSignature: "depositToRemote"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'depositToRemote', values: [BigNumberish, BigNumberish, BytesLike, AddressLike, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'depositToRemote', data: BytesLike): Result;
  }

  

  export interface IXReserve extends BaseContract {
    
    connect(runner?: ContractRunner | null): IXReserve;
    waitForDeployment(): Promise<this>;

    interface: IXReserveInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    depositToRemote: TypedContractMethod<
      [value: BigNumberish, remoteDomain: BigNumberish, remoteRecipient: BytesLike, localToken: AddressLike, maxFee: BigNumberish, hookData: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'depositToRemote'): TypedContractMethod<
      [value: BigNumberish, remoteDomain: BigNumberish, remoteRecipient: BytesLike, localToken: AddressLike, maxFee: BigNumberish, hookData: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }