/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockMessageTransmitterInterface extends Interface {
    getFunction(nameOrSignature: "receiveMessage" | "setShouldReturnFalse" | "setShouldRevert" | "shouldReturnFalse" | "shouldRevert" | "usdc" | "usedNonces"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'receiveMessage', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'setShouldReturnFalse', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setShouldRevert', values: [boolean]): string;
encodeFunctionData(functionFragment: 'shouldReturnFalse', values?: undefined): string;
encodeFunctionData(functionFragment: 'shouldRevert', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'usedNonces', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'receiveMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShouldReturnFalse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShouldRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldReturnFalse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedNonces', data: BytesLike): Result;
  }

  

  export interface MockMessageTransmitter extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockMessageTransmitter;
    waitForDeployment(): Promise<this>;

    interface: MockMessageTransmitterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    receiveMessage: TypedContractMethod<
      [message: BytesLike, arg1: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    setShouldReturnFalse: TypedContractMethod<
      [_shouldReturnFalse: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setShouldRevert: TypedContractMethod<
      [_shouldRevert: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    shouldReturnFalse: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    shouldRevert: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usedNonces: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'receiveMessage'): TypedContractMethod<
      [message: BytesLike, arg1: BytesLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setShouldReturnFalse'): TypedContractMethod<
      [_shouldReturnFalse: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setShouldRevert'): TypedContractMethod<
      [_shouldRevert: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shouldReturnFalse'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'shouldRevert'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usedNonces'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }