/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockXReserveInterface extends Interface {
    getFunction(nameOrSignature: "called" | "depositToRemote" | "lastHookData" | "lastLocalToken" | "lastMaxFee" | "lastRemoteDomain" | "lastRemoteRecipient" | "lastValue" | "setShouldRevert" | "shouldRevert"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'called', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositToRemote', values: [BigNumberish, BigNumberish, BytesLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'lastHookData', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastLocalToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastMaxFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastRemoteDomain', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastRemoteRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastValue', values?: undefined): string;
encodeFunctionData(functionFragment: 'setShouldRevert', values: [boolean]): string;
encodeFunctionData(functionFragment: 'shouldRevert', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'called', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositToRemote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastHookData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastLocalToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastMaxFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastRemoteDomain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastRemoteRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShouldRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldRevert', data: BytesLike): Result;
  }

  

  export interface MockXReserve extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockXReserve;
    waitForDeployment(): Promise<this>;

    interface: MockXReserveInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    called: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    depositToRemote: TypedContractMethod<
      [value: BigNumberish, remoteDomain: BigNumberish, remoteRecipient: BytesLike, localToken: AddressLike, maxFee: BigNumberish, hookData: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    lastHookData: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lastLocalToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lastMaxFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lastRemoteDomain: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lastRemoteRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lastValue: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setShouldRevert: TypedContractMethod<
      [_shouldRevert: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    shouldRevert: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'called'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'depositToRemote'): TypedContractMethod<
      [value: BigNumberish, remoteDomain: BigNumberish, remoteRecipient: BytesLike, localToken: AddressLike, maxFee: BigNumberish, hookData: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lastHookData'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastLocalToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastMaxFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastRemoteDomain'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastRemoteRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastValue'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setShouldRevert'): TypedContractMethod<
      [_shouldRevert: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shouldRevert'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }