/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as xReserveRouterSol from './XReserveRouter.sol/index.js';
export * as mocks from './mocks/index.js';