/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IXReserve, IXReserveInterface } from "../IXReserve.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "uint32",
        "name": "remoteDomain",
        "type": "uint32"
      },
      {
        "internalType": "bytes32",
        "name": "remoteRecipient",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "localToken",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "maxFee",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "hookData",
        "type": "bytes"
      }
    ],
    "name": "depositToRemote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IXReserve__factory {
    static readonly abi = _abi;
    static createInterface(): IXReserveInterface {
      return new Interface(_abi) as IXReserveInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IXReserve {
      return new Contract(address, _abi, runner) as unknown as IXReserve;
    }
  }
  