/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
    export type ForwardParamsStruct = {fallbackRecipient: AddressLike, remoteDomain: BigNumberish, remoteRecipient: BytesLike, maxFee: BigNumberish, hookData: BytesLike}

    export type ForwardParamsStructOutput = [fallbackRecipient: string, remoteDomain: bigint, remoteRecipient: string, maxFee: bigint, hookData: string] & {fallbackRecipient: string, remoteDomain: bigint, remoteRecipient: string, maxFee: bigint, hookData: string }
  

  export interface XReserveRouterInterface extends Interface {
    getFunction(nameOrSignature: "decodeForwardParams" | "operatorWallet" | "receiveAndForward" | "settledTransfers" | "transmitter" | "usdc" | "xReserve"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FallbackTriggered" | "Forwarded" | "OperatorRouted" | "RecoveredFromConsumedNonce"): EventFragment;

    encodeFunctionData(functionFragment: 'decodeForwardParams', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'operatorWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'receiveAndForward', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'settledTransfers', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transmitter', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'xReserve', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'decodeForwardParams', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatorWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveAndForward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settledTransfers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transmitter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'xReserve', data: BytesLike): Result;
  }

  
    export namespace FallbackTriggeredEvent {
      export type InputTuple = [fallbackRecipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [fallbackRecipient: string, amount: bigint];
      export interface OutputObject {fallbackRecipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ForwardedEvent {
      export type InputTuple = [remoteDomain: BigNumberish, remoteRecipient: BytesLike, amount: BigNumberish];
      export type OutputTuple = [remoteDomain: bigint, remoteRecipient: string, amount: bigint];
      export interface OutputObject {remoteDomain: bigint, remoteRecipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OperatorRoutedEvent {
      export type InputTuple = [transferId: BytesLike, nonce: BytesLike, amount: BigNumberish, reason: BigNumberish];
      export type OutputTuple = [transferId: string, nonce: string, amount: bigint, reason: bigint];
      export interface OutputObject {transferId: string, nonce: string, amount: bigint, reason: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecoveredFromConsumedNonceEvent {
      export type InputTuple = [nonce: BytesLike, amount: BigNumberish];
      export type OutputTuple = [nonce: string, amount: bigint];
      export interface OutputObject {nonce: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface XReserveRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): XReserveRouter;
    waitForDeployment(): Promise<this>;

    interface: XReserveRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decodeForwardParams: TypedContractMethod<
      [rawHookData: BytesLike, ],
      [ForwardParamsStructOutput],
      'view'
    >
    

    
    operatorWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    receiveAndForward: TypedContractMethod<
      [message: BytesLike, attestation: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    settledTransfers: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transmitter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    xReserve: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decodeForwardParams'): TypedContractMethod<
      [rawHookData: BytesLike, ],
      [ForwardParamsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'operatorWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'receiveAndForward'): TypedContractMethod<
      [message: BytesLike, attestation: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settledTransfers'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transmitter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'xReserve'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'FallbackTriggered'): TypedContractEvent<FallbackTriggeredEvent.InputTuple, FallbackTriggeredEvent.OutputTuple, FallbackTriggeredEvent.OutputObject>;
getEvent(key: 'Forwarded'): TypedContractEvent<ForwardedEvent.InputTuple, ForwardedEvent.OutputTuple, ForwardedEvent.OutputObject>;
getEvent(key: 'OperatorRouted'): TypedContractEvent<OperatorRoutedEvent.InputTuple, OperatorRoutedEvent.OutputTuple, OperatorRoutedEvent.OutputObject>;
getEvent(key: 'RecoveredFromConsumedNonce'): TypedContractEvent<RecoveredFromConsumedNonceEvent.InputTuple, RecoveredFromConsumedNonceEvent.OutputTuple, RecoveredFromConsumedNonceEvent.OutputObject>;

    filters: {
      
      'FallbackTriggered(address,uint256)': TypedContractEvent<FallbackTriggeredEvent.InputTuple, FallbackTriggeredEvent.OutputTuple, FallbackTriggeredEvent.OutputObject>;
      FallbackTriggered: TypedContractEvent<FallbackTriggeredEvent.InputTuple, FallbackTriggeredEvent.OutputTuple, FallbackTriggeredEvent.OutputObject>;
    

      'Forwarded(uint32,bytes32,uint256)': TypedContractEvent<ForwardedEvent.InputTuple, ForwardedEvent.OutputTuple, ForwardedEvent.OutputObject>;
      Forwarded: TypedContractEvent<ForwardedEvent.InputTuple, ForwardedEvent.OutputTuple, ForwardedEvent.OutputObject>;
    

      'OperatorRouted(bytes32,bytes32,uint256,uint8)': TypedContractEvent<OperatorRoutedEvent.InputTuple, OperatorRoutedEvent.OutputTuple, OperatorRoutedEvent.OutputObject>;
      OperatorRouted: TypedContractEvent<OperatorRoutedEvent.InputTuple, OperatorRoutedEvent.OutputTuple, OperatorRoutedEvent.OutputObject>;
    

      'RecoveredFromConsumedNonce(bytes32,uint256)': TypedContractEvent<RecoveredFromConsumedNonceEvent.InputTuple, RecoveredFromConsumedNonceEvent.OutputTuple, RecoveredFromConsumedNonceEvent.OutputObject>;
      RecoveredFromConsumedNonce: TypedContractEvent<RecoveredFromConsumedNonceEvent.InputTuple, RecoveredFromConsumedNonceEvent.OutputTuple, RecoveredFromConsumedNonceEvent.OutputObject>;
    
    };
  }